###
# GET Order
GET https://api.rechargeapps.com/orders/{{$dotenv RECHARGE_ORDER_ID}}
Content-Type: application/json
X-Recharge-Version: 2021-11
X-Recharge-Access-Token: {{$dotenv RECHARGE_ACCESS_TOKEN}}

###
# Get Stor info
GET https://api.rechargeapps.com/store
X-Recharge-Access-Token: {{$dotenv RECHARGE_ACCESS_TOKEN}}
X-Recharge-Version: 2021-11

###
# Add Webhook
POST https://api.rechargeapps.com/webhooks
Content-Type: application/json
X-Recharge-Access-Token: {{$dotenv RECHARGE_ACCESS_TOKEN}}
Accept: application/json

{
	"address": "{{$dotenv HEROKU_ENDPOINT}}/webhook/recharge/order-created--allow-all",
	"topic": "order/created"
}

###
# Update webhook endpoint
PUT https://api.rechargeapps.com/webhooks/{{$dotenv RECHARGE_WEBHOOK_ID}}
Content-Type: application/json
X-Recharge-Access-Token: {{$dotenv RECHARGE_ACCESS_TOKEN}}
Accept: application/json

{
	"address": "{{$dotenv HEROKU_ENDPOINT}}/webhook/recharge/order-created--allow-all"
}

###
# List webhooks
GET https://api.rechargeapps.com/webhooks
Content-Type: application/json
X-Recharge-Access-Token: {{$dotenv RECHARGE_ACCESS_TOKEN}}
Accept: application/json

###
# Delete webhooks
DELETE https://api.rechargeapps.com/webhooks/{{$dotenv RECHARGE_WEBHOOK_ID}}
Content-Type: application/json
X-Recharge-Access-Token: {{$dotenv RECHARGE_ACCESS_TOKEN}}
Accept: application/json

###
# Update subscription price
PUT https://api.rechargeapps.com/subscriptions/{{$dotenv SUBSCRIPTION_NUMBER}}
Content-Type: application/json
X-Recharge-Access-Token: {{$dotenv RECHARGE_ACCESS_TOKEN}}
Accept: application/json

{
  "price": 11.16
}
