### 
# Test API routes
GET http://localhost:3001/api/hello-world

###
# Test webhook routes
POST http://localhost:3001/webhook/hello-world
Content-Type: application/json

{
  "hello": "world"
}

###
# Order created
POST http://localhost:3001/webhook/recharge/order-created
Content-Type: application/json

< ./test_data/order.json

###
# Order created
POST http://localhost:3001/webhook/recharge/order-created--allow-all
Content-Type: application/json

< ./test_data/webhook_order.json


###
# Recharge Test with local

###
# List webhooks
GET https://api.rechargeapps.com/webhooks
Content-Type: application/json
X-Recharge-Access-Token: {{$dotenv RECHARGE_ACCESS_TOKEN}}
Accept: application/json


###
# Create Webhook
POST https://api.rechargeapps.com/webhooks
Content-Type: application/json
X-Recharge-Access-Token: {{$dotenv RECHARGE_ACCESS_TOKEN}}
Accept: application/json

{
	"address": "{{$dotenv NGROK_ENDPOINT}}/webhook/recharge/order-created--allow-all",
	"topic": "order/created"
}

###
# Update Webhook
PUT https://api.rechargeapps.com/webhooks/{{$dotenv RECHARGE_WEBHOOK_ID}}
Content-Type: application/json
X-Recharge-Access-Token: {{$dotenv RECHARGE_ACCESS_TOKEN}}
Accept: application/json

{
	"address": "{{$dotenv NGROK_ENDPOINT}}/webhook/recharge/order-created--allow-all",
	"topic": "order/created",
	"included_objects": []
}

###
# Delete Webhook
DELETE https://api.rechargeapps.com/webhooks/{{$dotenv RECHARGE_WEBHOOK_ID}}
Content-Type: application/json
X-Recharge-Access-Token: {{$dotenv RECHARGE_ACCESS_TOKEN}}
Accept: application/json
